language: node_js
node_js: stable
sudo: false
before_install: npm install -g grunt-cli
install: npm install
deploy:
  provider: npm
  email: ceberhardt@scottlogic.com
  on:
    tags: true
    branch: master
  api_key:
    secure: lvsGINL41daD8dcucBcKX0lTZi2POstY6DN8mhmi4czQr6rA0PFOS6+jzoqfkQDP/NNjeJ16s4v115O4CreJDQrMYT7BVbdLZAUTxosgsHA7BxVdZRUFxYtDnavzhVMKQmpWffsI30tyAnKv528X7PMWJ3na/lahpBVUbgf0xubYKvFC2SgVRgqqhDOYTPn1LeYOMLLhnmEEEuAWaQftA+Sz/IiGgEamxACOR5e3fFXV+7dI0rWKsGsP49YugnCb0cY3JIEdnmJd4h0E27fOeg5lXBRoR4HK1XQ7++tQZF4MvervxgNc4w7BP6NLdXVO8/UtV+uOr7mOsa8WRhMa3NXMUrhKJ8ZopHQ7oh/24o2ttkNFRMZcQbwrRmo1O1DxufdZaimS3qwfKhKKKDWapY5yJsYvbzjhEmGOMKK9YpmtIZhiCy+uQjGiOwUdRqbXuGvVk9eOY6GrmhRETxme5UTN8RSZhr32HlXizeeGvAxJQZsSuA5Ci3VjjKq62hez1tLZ3rC5R0DlymeirNqyFZ9OIUxUnbxKTJQRIj5YiUJPZZwuMRGC7SZvDoLD3FfpMROU/cKfXCjebHxzv2UUtyykU41zxGRXHew8zWTuqBKkWCjvAX1qj1RjIuF+dwfufxlxTcL921D3TRCplXF+BEAzwv0VxL5dub2Rz5CYfKo=
