language: node_js
node_js: stable
sudo: false
before_install: npm install -g grunt-cli
install: npm install
deploy:
  provider: npm
  email: ceberhardt@scottlogic.com
  api_key:
    secure: BBIJCvlrBiUHmWJctyzPqJQFcydjLAWT7l2EQSSpeF+P3KrN4bjuLIB41ukV1tOJ3cKMcq4Jm66Ro6OHXoFSLklNsitc1Q0cqutFFHivkdgkCNt7R/8/DM+SX10JYk8FDMccZFNqeCIzJcbk7fWc5Gs8T+fqkbS32g9f/E/UTCkWSzIEGmzkyNdXpOArGw2fPq7hpZIFIJXf5n9nwnLmWPi130MV/Q7znXI0iEz3EW2rN+w22Ph2MRkPf6rXeKCjWWCqOWIHxH+mkbTuT8S4DIn3CHcg3uvKRbiT3MOB7OZDce+XfEv9Qlw+efuWTEOvNdNcHIC7eDETDjVa1I52QDU1rpT1wOOPg+irqMOSqpjbHhMc3Ymvf/0+HEntJlOwNXgBT+Utdt7pBDwpaXoECg91l9YT52LQVOlVsW7L9BeSCfStarjKBseVe4flrAoihaue05/onO9/WjfulkJlDCADRjClr/4F2XQUoEbmHdHL8hjLOm5+BLVwFVW5cZXpU1HTrsKwrEM7jmaVXIKhzibPtVnRQZncJc1Y1eBu4brUwptJQKeFlelf23SmtToFJ4W7UrxtoPhe7CKUNH6CHmgX95rY6CAgA6N61M4o+cYAdKFk8xFQgmnKAxyyR8CQdOikn5xvs1LMTfVIJbsj1jTgaWSOJWBCkNkpxfHfNhs=
  on:
    tags: true
    branch: master
